New-ADOrganizationalUnit -Name "Thanks Cinco" -Path "DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Accounting" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Administration" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Brokerage" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Cinco Groups" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Continuous Improvement" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Dispatch" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Engineering" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Human Resources" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Information Technology" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Infrastructure" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "K and P" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Maintenance" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Marketing" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Operations" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Packaging" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Safety" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Sales" -Path "OU=Thanks Cinco,DC=cinco,DC=local"
New-ADOrganizationalUnit -Name "Warehousing" -Path "OU=Thanks Cinco,DC=cinco,DC=local"